# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single waveguide viewer.ui'
#
# Created: Sun Jul  8 15:06:42 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui


import numpy as np
import matplotlib.pyplot as plt
from interactive_plot import DragPlot
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    
    def myGraph(self):
        self.x = np.linspace(0,10*np.pi, 1000)
        self.y = np.sinc(self.x)
        self.fig = Figure((4,4))
        self.canvas = FigureCanvas(self.fig)
        self.canvas.setParent(self.MatplotlibRootPlot)

        self.axis = self.fig.add_subplot(111)
        self.line, = self.axis.plot(self.x, self.y)
        self.drag = DragPlot(self.line)
        
    def draw(self):
        self.canvas.draw()
    
    def connect(self):    
        self.connect(self.pushButton_reDraw, SIGNAL('clicked()'), self.draw)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(741, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(105)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.tabWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setMinimumSize(QtCore.QSize(275, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(275, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_ModeSelect = QtGui.QComboBox(self.frame_3)
        self.comboBox_ModeSelect.setMaximumSize(QtCore.QSize(275, 16777215))
        self.comboBox_ModeSelect.setObjectName(_fromUtf8("comboBox_ModeSelect"))
        self.comboBox_ModeSelect.addItem(_fromUtf8(""))
        self.comboBox_ModeSelect.addItem(_fromUtf8(""))
        self.comboBox_ModeSelect.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_ModeSelect)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_mValue = QtGui.QSpinBox(self.frame_4)
        self.spinBox_mValue.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_mValue.setObjectName(_fromUtf8("spinBox_mValue"))
        self.horizontalLayout_4.addWidget(self.spinBox_mValue)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_nvalue = QtGui.QSpinBox(self.frame_5)
        self.spinBox_nvalue.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_nvalue.setMinimum(1)
        self.spinBox_nvalue.setMaximum(10)
        self.spinBox_nvalue.setObjectName(_fromUtf8("spinBox_nvalue"))
        self.horizontalLayout_5.addWidget(self.spinBox_nvalue)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(155, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.doubleSpinBox_cValue = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_cValue.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_cValue.setMinimum(1.05)
        self.doubleSpinBox_cValue.setMaximum(10.0)
        self.doubleSpinBox_cValue.setSingleStep(0.2)
        self.doubleSpinBox_cValue.setProperty("value", 2.0)
        self.doubleSpinBox_cValue.setObjectName(_fromUtf8("doubleSpinBox_cValue"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_cValue)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.SelectModeOkButton = QtGui.QPushButton(self.frame_3)
        self.SelectModeOkButton.setObjectName(_fromUtf8("SelectModeOkButton"))
        self.verticalLayout_3.addWidget(self.SelectModeOkButton)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_6 = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.frame_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.label_5 = QtGui.QLabel(self.frame_6)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.frame_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.frame_7 = QtGui.QFrame(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_mValue = QtGui.QLabel(self.frame_7)
        self.label_mValue.setText(_fromUtf8(""))
        self.label_mValue.setObjectName(_fromUtf8("label_mValue"))
        self.horizontalLayout_6.addWidget(self.label_mValue)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_n = QtGui.QLabel(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_n.sizePolicy().hasHeightForWidth())
        self.label_n.setSizePolicy(sizePolicy)
        self.label_n.setObjectName(_fromUtf8("label_n"))
        self.horizontalLayout_7.addWidget(self.label_n)
        self.label_nValue = QtGui.QLabel(self.frame_8)
        self.label_nValue.setText(_fromUtf8(""))
        self.label_nValue.setObjectName(_fromUtf8("label_nValue"))
        self.horizontalLayout_7.addWidget(self.label_nValue)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.frame_6)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_c = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_c.sizePolicy().hasHeightForWidth())
        self.label_c.setSizePolicy(sizePolicy)
        self.label_c.setObjectName(_fromUtf8("label_c"))
        self.horizontalLayout_8.addWidget(self.label_c)
        self.label_cValue = QtGui.QLabel(self.frame_9)
        self.label_cValue.setText(_fromUtf8(""))
        self.label_cValue.setObjectName(_fromUtf8("label_cValue"))
        self.horizontalLayout_8.addWidget(self.label_cValue)
        self.verticalLayout_4.addWidget(self.frame_9)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.MatplotlibRootPlot = QtGui.QWidget(self.tab)
        self.MatplotlibRootPlot.setObjectName(_fromUtf8("MatplotlibRootPlot"))
        self.horizontalLayout_2.addWidget(self.MatplotlibRootPlot)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_CalculateRoot = QtGui.QPushButton(self.frame_2)
        self.pushButton_CalculateRoot.setObjectName(_fromUtf8("pushButton_CalculateRoot"))
        self.verticalLayout.addWidget(self.pushButton_CalculateRoot)
        self.pushButton_DefaultRoot = QtGui.QPushButton(self.frame_2)
        self.pushButton_DefaultRoot.setObjectName(_fromUtf8("pushButton_DefaultRoot"))
        self.verticalLayout.addWidget(self.pushButton_DefaultRoot)
        
        self.pushButton_reDraw = QtGui.QPushButton(self.frame_2)
        self.pushButton_reDraw.setObjectName(_fromUtf8("pushButton_reDraw"))
        self.verticalLayout.addWidget(self.pushButton_reDraw)
        
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_DefaultRoot, self.spinBox_mValue)
        MainWindow.setTabOrder(self.spinBox_mValue, self.comboBox_ModeSelect)
        MainWindow.setTabOrder(self.comboBox_ModeSelect, self.spinBox_nvalue)
        MainWindow.setTabOrder(self.spinBox_nvalue, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_CalculateRoot)
        MainWindow.setTabOrder(self.pushButton_CalculateRoot, self.SelectModeOkButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Waveguide Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ModeSelect.setItemText(0, QtGui.QApplication.translate("MainWindow", "Transverse Magnetic (TM)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ModeSelect.setItemText(1, QtGui.QApplication.translate("MainWindow", "Transverse Electric (TE)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ModeSelect.setItemText(2, QtGui.QApplication.translate("MainWindow", "Transverse Electric-Magnetic (TEM)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectModeOkButton.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Mode Information:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Each waveguide mode can be labeled by its (m,n) value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "c refers to the ratio of the outter radius to the inner radius", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "m = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_n.setText(QtGui.QApplication.translate("MainWindow", "n =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_c.setText(QtGui.QApplication.translate("MainWindow", "c = ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Select Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CalculateRoot.setText(QtGui.QApplication.translate("MainWindow", "Calculate Root", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DefaultRoot.setText(QtGui.QApplication.translate("MainWindow", "Default Root", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reDraw.setText(QtGui.QApplication.translate("MainWindow", "Redraw", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Find Root", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.myGraph()
    MainWindow.show()
    sys.exit(app.exec_())

